name: Hermes Streaming Engine

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  stream:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Download Video from Dropbox
        run: |
          # wget jauh lebih cepat dan simpel untuk link direct Dropbox
          wget -O lofi.mp4 "https://www.dropbox.com/scl/fi/9excxmzw9cb9e0q3ejzh9/lofi.mp4?rlkey=j87n5tn8kxs901p4nrqqv6on7&st=0itgzylv&dl=1"

      - name: Start Looping Stream
        run: |
          ffmpeg -re -stream_loop -1 -i lofi.mp4 \
          -c:v libx264 -preset veryfast -b:v 2500k -maxrate 2500k -bufsize 5000k \
          -pix_fmt yuv420p -g 120 -c:a aac -b:a 128k -ar 44100 \
          -f flv "rtmp://a.rtmp.youtube.com/live2/${{ secrets.YOUTUBE_STREAM_KEY }}"
