name: Hermes Streaming Engine

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  stream:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download Video from Google Drive
        run: |
          python3 -m pip install --upgrade gdown
          python3 -m gdown 14BscG_Lp_qQkVqJNfFN5W9wqCO_PRRxj -O lofi.mp4

      - name: Install FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Start Looping Stream
        env:
          # Manggil secret yang sudah kamu buat di list tadi
          YOUTUBE_KEY: ${{ secrets.YOUTUBE_STREAM_KEY }}
        run: |
          # Pakai RTMP standar biar gak kena error TLS/SSL
          ffmpeg -re -stream_loop -1 -i lofi.mp4 \
          -c:v libx264 -preset veryfast -b:v 2500k -maxrate 2500k -bufsize 5000k \
          -pix_fmt yuv420p -g 120 -c:a aac -b:a 128k -ar 44100 \
          -f flv "rtmp://a.rtmp.youtube.com/live2/$YOUTUBE_KEY"
