name: YouTube Bot Runner

on:
  workflow_dispatch:

jobs:
  bot-job:
    runs-on: ubuntu-latest  # LO PAKE UBUNTU, BUKAN WINDOWS
    timeout-minutes: 360

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install requests fake_useragent
          pip install fake_useragent playwright
          playwright install chromium


      
      - name: Keep alive
        run: |
          while true; do
            echo "[$(date)] Bot masih jalan..."
            sleep 300
          done
